const axios = require("axios");
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const system = {
  token: "QVJVSVo6SW5jb20jNzI0IQ==",
  url: "https://my338095.sapbydesign.com/sap/byd/odata/ana_businessanalytics_analytics.svc/RPZ19E8DA3EFFE9E02CA7CB66QueryResults?$select=CITEM_GROUP,TITEM_GROUP,CPRODUCT_ID,TPRODUCT_ID,CSALES_MEASURE_UNIT_CODE,TSALES_MEASURE_UNIT_CODE&$filter=(CPRODUCT_ID%20eq%20%27*ALCOHOL40%27)&$format=json",
};

export default function Home() {
  const putOrder = () => {
    axios
      .post("/api/order")
      .then((response) => {
        console.log(response);
      })
      .catch((err) => console.log(err));
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className="w-full py-8 flex justify-center items-center">
          <button
            onClick={putOrder}
            className="bg-blue-500 rounded-full text-white px-4 py-2"
          >
            Obtener unidad
          </button>
        </div>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
